language: node_js
node_js:
- '10.9'
dist: trusty
branches:
  only:
  - master
before_script:
  - npm install
script:
  - npm test
  - npm run build

deploy:
  - provider: pages
    local_dir: ./build
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master
